apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-izmir
spec:
  destination:
    name: ''
    namespace: traefik
    server: 'https://192.168.0.151:6443'
  source:
    path: helm/traefik
    repoURL: 'https://github.com/Thetatanga01/argocd'
    targetRevision: HEAD
    helm:
      valueFiles:
        - izmir-values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
