apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-istanbul
spec:
  destination:
    name: ''
    namespace: traefik
    server: 'https://10.10.10.10:6443'
  source:
    path: helm/traefik
    repoURL: 'https://github.com/Thetatanga01/argocd'
    targetRevision: HEAD
    helm:
      valueFiles:
        - istanbul-values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
